name: "Automated Build"

on: [push, pull_request]

jobs:
  create-build:
    runs-on: windows-latest
    steps:
      - name: "Download source"
        uses: actions/checkout@v2

      - name: "Download reference dlls"
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.REFS_REPO }}
          token: ${{ secrets.BUILD_PAT }}
          path: lib

      - name: "Setup .NET"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: "Restore dependencies"
        run: dotnet restore
        shell: pwsh

      - name: "Build"
        run: dotnet build -c Release --no-restore --output bin
        shell: pwsh

      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: bin/NoIntro.dll
